workflows:
  # ========================================
  # ZYEA CHAT APP (iOS) - Main Workflow
  # ========================================
  ios-workflow:
    name: Zyea Chat App iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "client/ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.zyea.hieudev"
        # App Store Connect API credentials
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        # Code signing certificate
        CERTIFICATE_PRIVATE_KEY: Encrypted(...)
      node: 18.17.0
      xcode: 15.2
      cocoapods: default

    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true

    scripts:
      - name: Set up environment
        script: |
          echo "Building Zyea Chat App for iOS"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          
      - name: Install npm dependencies
        script: |
          cd client
          npm ci --legacy-peer-deps
          
      - name: Check and configure API endpoint
        script: |
          cd client
          echo "Checking API configuration..."
          # You can set API URL here if needed
          # export REACT_APP_API_URL=https://your-api.com
          
      - name: Build React app
        script: |
          cd client
          export DISABLE_ESLINT_PLUGIN=true
          export CI=false
          npm run build
          echo "React build completed"
          ls -la build/
          
      - name: Install CocoaPods dependencies
        script: |
          cd client/ios/App
          pod install
          
      - name: Sync Capacitor with iOS
        script: |
          cd client
          npx cap sync ios --deployment
          
      - name: Update iOS bundle identifier and version
        script: |
          cd client/ios/App/App
          # Update Info.plist if needed
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName Zyea Chat" Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist || true
          
      - name: Set up code signing
        script: |
          cd client
          xcode-project use-profiles
          
      - name: Build iOS IPA
        script: |
          cd client
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --config Release
            
      - name: Export IPA with options
        script: |
          cd client
          # Use export options plist if available
          if [ -f ios-export-options.plist ]; then
            xcodebuild -exportArchive \
              -archivePath build/ios/App.xcarchive \
              -exportPath build/ios/ipa \
              -exportOptionsPlist ios-export-options.plist
          fi

    artifacts:
      - client/build/ios/ipa/*.ipa
      - client/build/ios/ipa/*.dSYM.zip
      - client/build/ios/*.xcarchive

    publishing:
      email:
        recipients:
          - hieudev@example.com
        notify:
          success: true
          failure: true
          
      # Publish to TestFlight (uncomment when ready)
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

  # ========================================
  # ANDROID BUILD (Optional)
  # ========================================
  android-workflow:
    name: Zyea Chat App Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      groups:
        - android_credentials
      vars:
        PACKAGE_NAME: "com.zyea.hieudev"
        KEYSTORE_PATH: $CM_KEYSTORE_PATH
        KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        KEY_ALIAS: $CM_KEY_ALIAS
        KEY_PASSWORD: $CM_KEY_PASSWORD
      node: 18.17.0
      java: 17
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: Install npm dependencies
        script: |
          cd client
          npm ci --legacy-peer-deps

      - name: Build React app
        script: |
          cd client
          export DISABLE_ESLINT_PLUGIN=true
          export CI=false
          npm run build

      - name: Sync Capacitor with Android
        script: |
          cd client
          npx cap sync android

      - name: Build Android APK/AAB
        script: |
          cd client/android
          chmod +x gradlew
          ./gradlew bundleRelease
          ./gradlew assembleRelease

    artifacts:
      - client/android/app/build/outputs/**/*.apk
      - client/android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - hieudev@example.com
        notify:
          success: true
          failure: true
