workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Add your code signing credentials here via Codemagic UI
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: v18.17.0
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Install dependencies
        script: |
          cd client
          npm install
      
      - name: Build web app
        script: |
          cd client
          npm run build
      
      - name: Install Capacitor CLI
        script: |
          cd client
          npm install -g @capacitor/cli
      
      - name: Add iOS platform
        script: |
          cd client
          npx cap add ios || echo "iOS platform already exists"
      
      - name: Sync Capacitor
        script: |
          cd client
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd client/ios/App
          pod install
      
      - name: Set up code signing
        script: |
          # Code signing will be handled automatically by Codemagic
          keychain initialize
      
      - name: Build iOS app
        script: |
          cd client/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive
      
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/export \
            -exportOptionsPlist client/ios/App/exportOptions.plist
    
    artifacts:
      - client/ios/App/build/App.ipa
      - $CM_BUILD_DIR/export/*.ipa
    
    publishing:
      email:
        recipients:
          - your-email@example.com


