name: Build iOS IPA

on:
  push:
    branches: [ main, master ]
    paths:
      - 'zalo-clone/client/**'
      - '.github/workflows/build-ios.yml'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'zalo-clone/client/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd zalo-clone/client
          npm ci
      
      - name: Build React app
        run: |
          cd zalo-clone/client
          npm run build
        env:
          REACT_APP_API_URL: http://192.168.0.101:5000/api
          REACT_APP_SOCKET_URL: http://192.168.0.101:5000
      
      - name: Setup Capacitor
        run: |
          cd zalo-clone/client
          npx cap sync ios || npx cap add ios
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install CocoaPods dependencies
        run: |
          cd zalo-clone/client/ios/App
          pod install || echo "Pod install failed, continuing..."
      
      # Import certificate và provisioning profile
      - name: Import Code-Signing Certificates
        if: ${{ secrets.IOS_CERTIFICATE_BASE64 != '' }}
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      
      - name: Import Provisioning Profile
        if: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 != '' }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
      
      # Build IPA
      - name: Build IPA
        if: ${{ secrets.IOS_CERTIFICATE_BASE64 != '' }}
        run: |
          cd zalo-clone/client/ios/App
          
          # Build archive
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            CODE_SIGN_IDENTITY="${{ secrets.IOS_CODE_SIGN_IDENTITY }}" \
            PROVISIONING_PROFILE_SPECIFIER="${{ secrets.IOS_PROVISIONING_PROFILE_NAME }}" \
            CODE_SIGN_STYLE=Manual
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ../../ios-export-options.plist \
            -exportPath $PWD/build \
            -allowProvisioningUpdates
      
      # Upload IPA artifact
      - name: Upload IPA
        if: ${{ secrets.IOS_CERTIFICATE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: Zyea-Plus-${{ github.run_number }}.ipa
          path: zalo-clone/client/ios/App/build/*.ipa
          retention-days: 30
      
      # Test build (without signing) if secrets not available
      - name: Test Build (No Signing)
        if: ${{ secrets.IOS_CERTIFICATE_BASE64 == '' }}
        run: |
          echo "⚠️ iOS Certificates not configured"
          echo "ℹ️ To build IPA, add these secrets to GitHub:"
          echo "  - IOS_CERTIFICATE_BASE64"
          echo "  - IOS_CERTIFICATE_PASSWORD"
          echo "  - IOS_PROVISIONING_PROFILE_BASE64"
          echo "  - IOS_PROVISIONING_PROFILE_NAME"
          echo "  - IOS_CODE_SIGN_IDENTITY"
          echo ""
          echo "✅ React app built successfully!"
          echo "✅ Capacitor sync completed!"
          echo ""
          echo "📖 See BUILD_IPA_GUIDE.md for setup instructions"
