workflows:
  expo-ios-workflow:
    name: Build Expo iOS IPA Unsigned
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.18.0
      npm: 10.8.2
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-expo
          npm ci
      - name: Prebuild iOS with Expo
        script: |
          cd mobile-expo
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods
        script: |
          cd mobile-expo/ios
          pod install
      - name: Build IPA (Unsigned)
        script: |
          cd mobile-expo/ios
          xcodebuild clean archive \
            -workspace *.xcworkspace \
            -scheme $(find . -name "*.xcworkspace" -exec basename {} .xcworkspace \;) \
            -configuration Release \
            -archivePath ../build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
            -archivePath ../build/App.xcarchive \
            -exportPath ../build/ipa \
            -exportOptionsPlist ../ios/exportOptions.plist
    artifacts:
      - mobile-expo/build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

