name: Build iOS IPA (Unsigned)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'client/**'
      - '.github/workflows/build-ios.yml'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Cho phép trigger thủ công

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd client
          npm install
      
      - name: Build React app
        run: |
          cd client
          npm run build
        env:
          REACT_APP_API_URL: https://your-api-url.com/api
          REACT_APP_SOCKET_URL: https://your-api-url.com
      
      - name: Setup Capacitor iOS
        run: |
          cd client
          npx cap add ios || echo "iOS already added"
          npx cap sync ios
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install CocoaPods dependencies
        run: |
          cd client/ios/App
          pod install
      
      - name: Build iOS App (Unsigned)
        run: |
          cd client/ios/App
          
          # Build without code signing
          xcodebuild clean build \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_ENTITLEMENTS="" \
            DEVELOPMENT_TEAM=""
      
      - name: Create IPA (Unsigned)
        run: |
          cd client/ios/App
          
          # Tạo thư mục Payload
          mkdir -p Payload
          
          # Copy .app vào Payload
          cp -r build/Build/Products/Release-iphoneos/App.app Payload/
          
          # Tạo file IPA (chỉ là file ZIP)
          zip -r ZyeaPlus-unsigned.ipa Payload
          
          # Di chuyển IPA ra ngoài
          mv ZyeaPlus-unsigned.ipa ../../
          
          echo "✅ IPA unsigned đã được tạo!"
      
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZyeaPlus-unsigned-${{ github.run_number }}.ipa
          path: client/ZyeaPlus-unsigned.ipa
          retention-days: 30
      
      - name: Build Summary
        run: |
          echo "🎉 BUILD THÀNH CÔNG!"
          echo ""
          echo "📦 File IPA unsigned đã sẵn sàng!"
          echo "📥 Download từ Artifacts tab phía trên"
          echo ""
          echo "🔐 CÁCH KÝ BẰNG ESIGN:"
          echo "1. Download file IPA từ Artifacts"
          echo "2. Cài ESign trên iPhone (https://esign.yyyue.xyz)"
          echo "3. Import file IPA vào ESign"
          echo "4. Click 'Sign' để tự ký"
          echo "5. Install app đã ký lên iPhone"
          echo ""
          echo "⚠️  Lưu ý:"
          echo "- Chứng chỉ tự ký chỉ hoạt động 7 ngày"
          echo "- Cần re-sign mỗi 7 ngày"
          echo "- Không cần Apple Developer Account"
          echo ""
          echo "📱 App: Zyea+ Chat"
          echo "🏷️  Build #${{ github.run_number }}"
