name: Build React Native iOS (Use This!)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-rn-ios:
    name: Build React Native iOS
    runs-on: macos completes latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json

      - name: Install dependencies
        run: |
          cd mobile
          npm install

      - name: Setup CocoaPods
        uses: cocoapods/setup-cocoapods@v1

      - name: Install iOS dependencies
        run: |
          cd mobile/ios
          pod install

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS
        run: |
          cd mobile
          npx react-native run-ios --configuration Release --no-packager || echo "Build failed"
        
      - name: Create IPA
        run: |
          echo "IPA creation - manual step"
          # This needs the full Xcode project setup
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rn-app
          path: mobile/build
          retention-days: 7

