name: Build iOS IPA

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build info
        run: |
          echo "📱 Build iOS IPA"
          echo "✅ Workflow is ready"
          echo ""
          echo "⚠️ Note: iOS folder needed for build"
          echo ""
          echo "To add iOS:"
          echo "1. cd client"
          echo "2. npm install @capacitor/ios"
          echo "3. npx cap add ios"
          echo "4. npx cap sync ios"
          
      - name: Upload info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: README.md
          retention-days: 1
