name: Build iOS IPA

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Setup CocoaPods
        uses: cocoapods/setup-cocoapods@v1
        with:
          version: '1.14.0'

      - name: Install dependencies
        run: |
          cd client
          npm ci --legacy-peer-deps

      - name: Build React app
        env:
          DISABLE_ESLINT_PLUGIN: true
          CI: false
        run: |
          cd client
          npm run build

      - name: Setup Capacitor iOS
        run: |
          cd client
          npx cap sync ios

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Certificate & Provisioning Profile
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          certs-keychain-password: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}

      # Alternative: Manual signing
      - name: Create certificate & profile (Alternative)
        if: ${{ secrets.IOS_P12_BASE64 == '' }}
        run: |
          # Create keychain
          security create-keychain -p "${{ secrets.IOS_KEYCHAIN_PASSWORD }}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.IOS_KEYCHAIN_PASSWORD }}" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Build IPA
        run: |
          cd client/ios/App
          pod install
          
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath client/ios/App/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath ./output

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZyeaApp-IPA
          path: output/*.ipa
          retention-days: 30

      - name: Create Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: output/*.ipa
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

