name: Build iOS IPA (Unsigned)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'client/**'
      - '.github/workflows/build-ios.yml'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Cho phép trigger thủ công

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd client
          npm install
      
      - name: Build React app
        run: |
          cd client
          echo "🏗️  Building React app for iOS..."
          echo "📡 API URL: ${{ secrets.API_URL || 'http://192.168.0.102:5000/api' }}"
          echo "🔌 Socket URL: ${{ secrets.SOCKET_URL || 'http://192.168.0.102:5000' }}"
          npm run build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          GENERATE_SOURCEMAP: false
          # Use GitHub Secrets if available, otherwise use default
          REACT_APP_API_URL: ${{ secrets.API_URL || 'http://192.168.0.102:5000/api' }}
          REACT_APP_SOCKET_URL: ${{ secrets.SOCKET_URL || 'http://192.168.0.102:5000' }}
      
      - name: Generate iOS Assets (Icons & Splash)
        run: |
          cd client
          # Generate icon.png và splash.png từ JPG nếu chưa có
          node generate-assets.js || echo "Assets already exist"
          # Install Capacitor Assets tool
          npm install @capacitor/assets --save-dev
      
      - name: Setup Capacitor iOS
        run: |
          cd client
          npx cap add ios || echo "iOS already added"
          
      - name: Configure iOS Info.plist (HTTP & Permissions)
        run: |
          cd client
          node configure-ios-info-plist.js
          echo "✅ iOS Info.plist configured!"
          
      - name: Generate iOS Native Assets (CRITICAL for Splash Screen)
        run: |
          cd client
          # Generate ALL iOS native assets including splash screens
          echo "📱 Generating iOS native splash screens and icons..."
          npx @capacitor/assets generate \
            --iconBackgroundColor "#0084ff" \
            --iconBackgroundColorDark "#0084ff" \
            --splashBackgroundColor "#0084ff" \
            --splashBackgroundColorDark "#0084ff" \
            --ios
          echo "✅ iOS assets generated!"
          # Verify splash screens were created
          ls -la ios/App/App/Assets.xcassets/Splash.imageset/ || echo "⚠️ Splash images not found"
          
      - name: Sync Capacitor
        run: |
          cd client
          npx cap sync ios
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install CocoaPods dependencies
        run: |
          cd client/ios/App
          pod install
      
      - name: Build iOS App (Unsigned)
        run: |
          cd client/ios/App
          
          # Build without code signing
          xcodebuild clean build \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGN_ENTITLEMENTS="" \
            DEVELOPMENT_TEAM=""
      
      - name: Create IPA (Unsigned)
        run: |
          cd client/ios/App
          
          # Tạo thư mục Payload
          mkdir -p Payload
          
          # Copy .app vào Payload
          cp -r build/Build/Products/Release-iphoneos/App.app Payload/
          
          # Tạo file IPA (chỉ là file ZIP)
          zip -r ZyeaPlus-unsigned.ipa Payload
          
          # Di chuyển IPA ra ngoài
          mv ZyeaPlus-unsigned.ipa ../../
          
          echo "✅ IPA unsigned đã được tạo!"
      
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZyeaPlus-unsigned-${{ github.run_number }}.ipa
          path: client/ZyeaPlus-unsigned.ipa
          retention-days: 30
      
      - name: Build Summary
        run: |
          echo "🎉 BUILD THÀNH CÔNG!"
          echo ""
          echo "📦 File IPA unsigned đã sẵn sàng!"
          echo "📥 Download từ Artifacts tab phía trên"
          echo ""
          echo "🔐 CÁCH KÝ BẰNG ESIGN:"
          echo "1. Download file IPA từ Artifacts"
          echo "2. Cài ESign trên iPhone (https://esign.yyyue.xyz)"
          echo "3. Import file IPA vào ESign"
          echo "4. Click 'Sign' để tự ký"
          echo "5. Install app đã ký lên iPhone"
          echo ""
          echo "⚠️  Lưu ý:"
          echo "- Chứng chỉ tự ký chỉ hoạt động 7 ngày"
          echo "- Cần re-sign mỗi 7 ngày"
          echo "- Không cần Apple Developer Account"
          echo ""
          echo "📱 App: Zyea+ Chat"
          echo "🏷️  Build #${{ github.run_number }}"
