name: Build Unsigned IPA (for esign)

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'
          
      - name: Install dependencies
        working-directory: client
        run: |
          npm install --legacy-peer-deps
          
      - name: Build React app
        working-directory: client
        env:
          DISABLE_ESLINT_PLUGIN: true
          CI: false
        run: |
          npm run build
          echo "✅ React build completed"
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
          
      - name: Install CocoaPods dependencies
        working-directory: client/ios/App
        run: |
          pod install --repo-update
          
      - name: Sync Capacitor
        working-directory: client
        run: |
          npx cap sync ios
          
      - name: Configure iOS project
        working-directory: client/ios/App/App
        run: |
          # Update app display name
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName 'Zyea Chat'" Info.plist || true
          
          # Update version
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" Info.plist || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" Info.plist || true
          
          echo "✅ iOS project configured"
          
      - name: Build unsigned archive
        working-directory: client/ios/App
        run: |
          # Build archive without code signing
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
            
          echo "✅ Archive created (unsigned)"
          
      - name: Create IPA from archive
        working-directory: client/ios/App
        run: |
          # Create Payload directory
          mkdir -p build/Payload
          
          # Copy .app to Payload
          cp -r build/App.xcarchive/Products/Applications/App.app build/Payload/
          
          # Create IPA (just a zip file)
          cd build
          zip -r ZyeaChat-unsigned-${{ github.run_number }}.ipa Payload
          
          echo "✅ Unsigned IPA created"
          ls -lh ZyeaChat-unsigned-*.ipa
          pwd
          
      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ZyeaChat-unsigned-${{ github.run_number }}
          path: client/ios/App/build/ZyeaChat-unsigned-*.ipa
          retention-days: 30
          
      - name: Generate build summary
        run: |
          echo "## 📱 Unsigned IPA Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Number:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Unsigned IPA created successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📥 Cách sử dụng:" >> $GITHUB_STEP_SUMMARY
          echo "1. Download IPA từ Artifacts phía dưới" >> $GITHUB_STEP_SUMMARY
          echo "2. Sử dụng **ESign**, **AltStore**, **Sideloadly** hoặc tool tương tự để ký" >> $GITHUB_STEP_SUMMARY
          echo "3. Cài đặt IPA đã ký lên iPhone" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔑 Các tool phổ biến để ký IPA:" >> $GITHUB_STEP_SUMMARY
          echo "- **ESign** (iOS): Ký trực tiếp trên iPhone/iPad" >> $GITHUB_STEP_SUMMARY
          echo "- **AltStore** (PC/Mac): Ký qua AltServer" >> $GITHUB_STEP_SUMMARY
          echo "- **Sideloadly** (PC/Mac): Ký và cài đặt" >> $GITHUB_STEP_SUMMARY
          echo "- **iOS App Signer** (Mac): Ký với certificate riêng" >> $GITHUB_STEP_SUMMARY
