name: Build Capacitor iOS IPA

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: |
          cd client
          npm ci --legacy-peer-deps

      - name: Build web app
        run: |
          cd client
          npm run build

      - name: Sync Capacitor iOS
        run: |
          cd client
          npx cap sync ios

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build web app
        run: |
          cd client
          npm run build

      - name: Check for iOS folder
        run: |
          ls -la client/ios || echo "iOS folder not found"
          ls -la client/ios/App || echo "iOS/App folder not found"
        
      - name: Setup Capacitor iOS (if needed)
        run: |
          cd client
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync ios || echo "Sync skipped if already synced"
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Check iOS folder
        run: |
          echo "Checking for iOS folder..."
          ls -la client/ || echo "client/ not found"
          ls -la client/ios/ || echo "iOS folder not found - need to add iOS"

      - name: Export IPA
        run: |
          cd client/ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: capacitor-ipa
          path: client/ios/App/build/ipa/*.ipa
          retention-days: 30

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: client/ios/App/build/ipa/*.ipa
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          name: capacitor-ipa
          path: client/ios/App/build/ipa/*.ipa
          retention-days: 30

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: client/ios/App/build/ipa/*.ipa
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

