name: Build iOS Apps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      app_to_build:
        description: 'Which app to build'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - messenger
          - zyeaplus

jobs:
  build-messenger-ios:
    name: Build Messenger iOS
    runs-on: macos-latest
    if: github.event.inputs.app_to_build == 'messenger' || github.event.inputs.app_to_build == 'both' || github.event_name != 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Build React app
        working-directory: ./client
        run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Setup Capacitor
        working-directory: ./client
        run: |
          npx cap sync ios

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS app
        working-directory: ./client/ios/App
        run: |
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath ./build/App.xcarchive \
            archive

      - name: Export IPA
        working-directory: ./client/ios/App
        run: |
          xcodebuild -exportArchive \
            -archivePath ./build/App.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist ../../ios-export-options.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: Messenger-iOS
          path: client/ios/App/build/*.ipa
          retention-days: 30

  build-zyeaplus-ios:
    name: Build Zyea+ iOS
    runs-on: macos-latest
    if: github.event.inputs.app_to_build == 'zyeaplus' || github.event.inputs.app_to_build == 'both' || github.event_name != 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: zyea-plus-app/package-lock.json

      - name: Install dependencies
        working-directory: ./zyea-plus-app
        run: npm ci

      - name: Build React app
        working-directory: ./zyea-plus-app
        run: npm run build
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Setup Capacitor
        working-directory: ./zyea-plus-app
        run: |
          npx cap add ios || true
          npx cap sync ios

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS app
        working-directory: ./zyea-plus-app/ios/App
        run: |
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath ./build/App.xcarchive \
            archive

      - name: Export IPA
        working-directory: ./zyea-plus-app/ios/App
        run: |
          xcodebuild -exportArchive \
            -archivePath ./build/App.xcarchive \
            -exportPath ./build \
            -exportOptionsPlist ../../ios-export-options.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZyeaPlus-iOS
          path: zyea-plus-app/ios/App/build/*.ipa
          retention-days: 30
